FROM alpine:3.18

LABEL org.opencontainers.image.authors="Seppe Volkaerts <contact@seppevolkaerts.be>"
LABEL org.opencontainers.image.url="https://github.com/Cybermaxke/terraria-helm-charts"
LABEL org.opencontainers.image.description="Tools used by Terraria helm charts"
LABEL org.opencontainers.image.source="https://github.com/Cybermaxke/terraria-helm-charts/blob/master/images/tools/Dockerfile"

RUN apk add --update-cache unzip curl socat
